
fecov <- function (x, n.ahead) {
  n.par <- sapply(x$varresult, function(x) summary(x)$df[2])
  sigma.u <- crossprod(resid(x))/n.par
  Sigma.yh <- array(NA, dim = c(x$K, x$K, n.ahead))
  Sigma.yh[, , 1] <- sigma.u
  Phi <- Phi(x, nstep = n.ahead)
  if (n.ahead > 1) {
    for (i in 2:n.ahead) {
      temp <- matrix(0, nrow = x$K, ncol = x$K)
      for (j in 2:i) {
        temp <- temp + Phi[, , j] %*% sigma.u %*% t(Phi[, 
                                                        , j])
      }
      Sigma.yh[, , i] <- temp + Sigma.yh[, , 1]
    }
  }
  return(Sigma.yh)
}

var_decomp <- function (x, n.ahead = 10, ...) {
  if (!(class(x) == "varest")) {
    stop("\nPlease provide an object of class 'varest', generated by 'VAR()'.\n")
  }
  n.ahead <- abs(as.integer(n.ahead))
  K <- x$K
  p <- x$p
  ynames <- colnames(x$datamat[, 1:K])
  msey <- fecov(x, n.ahead = n.ahead)
  Psi <- Psi(x, nstep = n.ahead)
  mse <- matrix(NA, nrow = n.ahead, ncol = K)
  Omega <- array(0, dim = c(n.ahead, K, K))
  for (i in 1:n.ahead) {
    
    
    mse[i, ] <- diag(msey[, , i])
    temp <- matrix(0, K, K)
    for (l in 1:K) {
      for (m in 1:K) {
        for (j in 1:i) {
          temp[l, m] <- temp[l, m] + Psi[l, m, j]^2
        }
      }
    }
    temp <- temp
    for (j in 1:K) {
      Omega[i, , j] <- temp[j, ]
    }
    
    
  }
  result <- list()
  for (i in 1:K) {
    result[[i]] <- matrix(Omega[, , i], nrow = n.ahead, ncol = K)
    colnames(result[[i]]) <- ynames
  }
  colnames(mse) <- ynames
  result[[K+1]] <- mse
  names(result) <- c(ynames,"mse")
  return(result)
}
##### Funcion ####

get_fevd <- function(model){
  var_dec <- model %>% var_decomp() 
  
  get_data <- function(i){
    df <- var_dec[[i]] %>% 
      as_tibble %>%
      mutate(shock=names(var_dec[i]))
  }
  
  df <- do.call("rbind",
                lapply(1:(length(var_dec)-1),get_data) ) %>%
    dplyr::filter(!grepl("PC",shock))
  
  prueba <- df %>% 
    select(contains("PC")) 
  
  a <- pca$rotation[,1:nfac] 
  b <- matrix(rep(0,100),ncol=10,nrow=10) 
  c <- as.matrix(prueba) 
  for( i in 1:10){
    b[i,i] <- c[1,i]
  }
  d <- pca$rotation[,1:nfac] %*% b %*% t(pca$rotation[,1:nfac])
  
  %>%  
    as_tibble %>% 
    mutate(cons=row.names(.) %>% as.numeric) %>% 
    gather(key=var,
           value=pred,
           -cons) 
  
  return(df)
}

z <- get_fevd(model)


